steps:
  # placeholder step
  - id: 'branch-name'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "-------------------------"
        echo "$BRANCH_NAME"
        echo "-------------------------"

  - id: 'terraform-init'
    name: 'hashicorp/terraform:1.0.0'
    script: terraform init
    
options:
  logging: CLOUD_LOGGING_ONLY