steps:
  
  - id: 'branch-name'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "-------------------------"
        echo "$BRANCH_NAME"
        echo "-------------------------"

  - id: 'tests'
    name: 'python'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        cd tests
        pytest -q tests.py

  - id: 'terraform-init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - | 
        terraform init -reconfigure

  - id: 'terraform-plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - | 
        terraform plan -var "project=${PROJECT_ID}"

  - id: 'terraform-apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - | 
        terraform apply --auto-approve -var "project=${PROJECT_ID}"

options:
  logging: CLOUD_LOGGING_ONLY